// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe0PnHW4ZqxoUaFoe4Y0nFc0eqdtsoEx4',
    appId: '1:1010195624522:web:4e6679bcea84fab7c62cb3',
    messagingSenderId: '1010195624522',
    projectId: 'test-p5hmgg',
    authDomain: 'test-p5hmgg.firebaseapp.com',
    storageBucket: 'test-p5hmgg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoIoURUpxR_03DPLm541s9no0bctsU61k',
    appId: '1:1010195624522:android:bf4f8774bc020c6fc62cb3',
    messagingSenderId: '1010195624522',
    projectId: 'test-p5hmgg',
    storageBucket: 'test-p5hmgg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTIO90Gw5oGBvvJaMEcd_KdDZTn7ATgOY',
    appId: '1:1010195624522:ios:52c848ebf5cd688bc62cb3',
    messagingSenderId: '1010195624522',
    projectId: 'test-p5hmgg',
    storageBucket: 'test-p5hmgg.appspot.com',
    androidClientId: '1010195624522-10ovmojrkmknovvou8vnlk4mid71r8ue.apps.googleusercontent.com',
    iosClientId: '1010195624522-b4eb1to2qlc37qnjeur16s8urbq38aa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.companyEmpo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTIO90Gw5oGBvvJaMEcd_KdDZTn7ATgOY',
    appId: '1:1010195624522:ios:52c848ebf5cd688bc62cb3',
    messagingSenderId: '1010195624522',
    projectId: 'test-p5hmgg',
    storageBucket: 'test-p5hmgg.appspot.com',
    androidClientId: '1010195624522-10ovmojrkmknovvou8vnlk4mid71r8ue.apps.googleusercontent.com',
    iosClientId: '1010195624522-b4eb1to2qlc37qnjeur16s8urbq38aa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.companyEmpo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe0PnHW4ZqxoUaFoe4Y0nFc0eqdtsoEx4',
    appId: '1:1010195624522:web:b00d0612e0f48cdfc62cb3',
    messagingSenderId: '1010195624522',
    projectId: 'test-p5hmgg',
    authDomain: 'test-p5hmgg.firebaseapp.com',
    storageBucket: 'test-p5hmgg.appspot.com',
  );

}